### ISSUE TITLE
unordered stops and shapes.shape_dist_traveled

### ISSUE THREAD

**Issue by antrim** [MobilityData/gtfs-flex#19]
This existing text (that I wrote in f05566f67812d76368cd1c27c5bbd441f643638c) is atrocious:

> Note that if a shape_id is specified for a trip that includes stops where unordered = 1, then shape_dist_traveled must be specified in stop_times.txt and shapes.txt. The correspondence of shape_dist_traveled values must make it clear that there is no alignment specified for the block of deviation points.

Opening an issue to go back and clarify that:

* there should be no shape/alignment for travel among unordered stops
* shape_dist_traveled is needed to clearly match the alignment to ordered stops

Using an example might be good.

**Comment by abyrd** [comment]
I was just reading this section of the spec and came to find/open an issue about this wording. While I wouldn't use the word "atrocious" I am unable to understand what the second sentence means. I also don't understand the two explanatory bullet points. I fully agree that there should be no shape / alignment for unordered stops, but how does the fact that the route contains unordered stops make shape_dist_traveled more necessary?

**Comment by antrim** [comment]
This part of the draft spec may change significantly.

But here is what I meant: "Unordered stops" would represent a break in the alignment. shape_dist_traveled in shapes.txt and stop_times.txt would be necessary to indicate where that alignment breaks and then resumes. Here's a diagram where shape_dist_traveled values are shown in magenta.

![image](https://user-images.githubusercontent.com/6495639/44939903-cc7aa480-ad3d-11e8-862e-a1c5503c8d54.png)

Maybe shape_dist_traveled wouldn't be as necessary as I am assuming for consuming software.

**Comment by abyrd** [comment]
If I'm not mistaken, the process of stop-to-shape matching will be the same with or without unordered stops. If shape_dist_traveled is supplied for shapes, the field with the same name on stops situates them along the shape. If shape_dist_traveled is not supplied, the stops are simply projected to the closest point on the shape.

**Comment by antrim** [comment]
You're right. Right now, some software does benefit from shape_dist_traveled in stop_times in some circumstances, which we discussed in the GTFS Best Practices: http://gtfs.org/best-practices/#stop_times_6

So, I don't think that stop_times.shape_dist_traveled would be a requirement for GTFS-flex, but might be a recommendation in some circumstances. And, the spec would need to define how shape_dist_traveled should increment (or not) to indicate the break in the alignment.

But, notions around unordered stops may change significantly.
