### ISSUE TITLE
routes.txt changes?

### ISSUE THREAD

**Issue by tsherlockcraig** [MobilityData/gtfs-flex#23]
The diagram of the GTFS-flex model indicates that routes.txt is an edited file, but I don't see a reference to changes to routes.txt in the spec.

**Comment by nihit-jain-ibigroup** [comment]
I believe the only real change to routes.txt is the addition of Call-n-Ride
route information, just so that any combined trip planner can reference
both fixed route and flexible routes together.

**Comment by antrim** [comment]
But there is no an additional routes.txt field in the draft spec.
