### ISSUE TITLE
what is the "direct travel time"?

### ISSUE THREAD

**Issue by tsherlockcraig** [MobilityData/gtfs-flex#24]
The reference definition of `drt_max_travel_time` refers to values that are a multiple of the "direct travel time".

```
This time may be expressed as a value (minutes), or as an arithmetic function where t=[direct travel time]. For example, the formula t*2.5+5 indicates that the maximum travel time for the passenger's demand-responsive travel leg is 30 minutes if the direct travel time is 10 minutes.
```

What exactly does "direct travel time" mean? Is this supposed to mean "drive time" or something else?

**Comment by antrim** [comment]
Direct travel time = drive time for most direct path, no additional stops

Sent from my phone

**Comment by thomastrillium** [comment]
Mind if I spell this out a bit more? I'm thinking I'd just use the phrase "drive time assuming there are no other stops".

**Comment by antrim** [comment]
Sounds good.

**Comment by ed-g** [comment]
Is this the "drive time" calculated between two sequential stops in stop-times, or the "drive time" along the entire trip?

Can you give a simple example?

**Comment by thomastrillium** [comment]
Drive time is unrelated to stop_times. It is the car drive time from one point to another, if you queried otp for traveling between origin and destination by car. 

Thomas Craig ~mobile

**Comment by ed-g** [comment]
What are the origin and destination in the calculation. The users's start/end location to the end point of the trip? Or the nearest point to the trip alignment?

**Comment by thomastrillium** [comment]
Users start and end locations on the drt leg of the trip. 

Thomas Craig ~mobile

**Comment by ed-g** [comment]
The portion of their travel via the transit route which is drt enabled? In other words get on at (lat1,lon1) get off at stop x at (lat2,lon2). Direct travel time is the drive time between (lat1,lon1) and (lat2,lon2).

**Comment by ed-g** [comment]
Got it, thanks!

**Comment by thomastrillium** [comment]
Yes. 

Thomas Craig ~mobile
