### ISSUE TITLE
force direction for unordered stops

### ISSUE THREAD

**Issue by wherbawi** [MobilityData/gtfs-flex#29]
A constraint force direction is useful for unordered stops. This is to prevent traveling passengers backwards then forwards. The scenario is like this: We have a set of unordered stops that can be served in any order. However, once a customer trip is scheduled, for example, with pickup at stop C (stop sequence 3) and delivery at stop E (stop sequence 5), this trip cannot be interrupted with a pickup/delivery at stop B (stop sequence 2) or any stop with stop sequence < 3. The trip can be interrupted with a pickup/delivery at stop D  (stop sequence 4). This constraint can be specified as special value of the field unordered (e.g. unordered = 2 means force direction) in stop_times.txt

**Comment by abyrd** [comment]
I believe that the "unordered stops" field is intended for services that are, at least from the perspective of the rider, truly unordered. If the stops can be served "in any order" then by definition they are not constrained to be served in any particular order. It seems to me that "forcing direction" is synonymous with "ordering".

The operator might have any number of additional constraints for efficiency or to meet level of service requirements, but these are operational details that are not relevant to a single passenger looking for travel information.

**Comment by t2gran** [comment]
What use case do you want to support by this constraint?

From the perspective of travel planning (implementing FLEX in e.g. OTP) i don´t see that this would give us anything. Maybe if we had realtime data we could say that going back to pick-up riders is not legal, but the use case is very limited and complex to implement.
