### ISSUE TITLE
Documentation: reference implementations & example datasets

### ISSUE THREAD

**Issue by antrim** [MobilityData/gtfs-flex#33]
Let's link to the GTFS-flex projects in motion from the repo homepage!

e.g. OpenTripPlanner:
https://github.com/camsys/OpenTripPlanner/tree/vtrans-gtfsflex
https://trilliumtransit.com/2016/10/21/announcing-the-flexible-transit-trip-planner/
https://trilliumtransit.com/2017/03/10/flexible-trip-planner-update-project-kick-off/
https://trilliumtransit.com/2017/09/01/alpha-release-of-the-flexible-trip-planner/

And, draft GTFS-flex datasets.

**Comment by barbeau** [comment]
:+1:

**Comment by RideSchedules** [comment]
Try these: 

Sonoma County, CA
Addison County, VT
Green Mountain, VT 
Moover!, VT
Special Services Transportation Agency, VT
The Current, VT
Ceres Area Transit, CA
Bus Lines of Turlock, CA
