### ISSUE TITLE
Stop sequence numbers for unordered stops

### ISSUE THREAD

**Issue by abyrd** [MobilityData/gtfs-flex#36]
The current spec adds a new field to stop_times to flag unordered stops. According to the examples, within blocks of unordered stops the stop_sequence field is still present with unique, increasing integers.

Observations:
1. It seems contradictory for unordered stops to have increasing sequence numbers.
2. It seems unnecessary to extend stop_times with a new boolean field when we already have a mechanism for expressing ordering or lack thereof (the sequence number).
3. The new `unordered` field will be ignored by legacy software, which will silently misinterpret the unordered trip as an ordered one.

Proposal:
Indicate unordered stops with repeating sequence numbers, and without additional flags. This convention would make the data appear invalid to legacy systems, raise red flags and prevent older consumers from misinterpreting it and misinforming customers.

A partially unordered trip (leaving regularly from checkpoint stop0) would then have stop times like this:
```
trip_id,arrival_time,departure_time,stop_id,stop_sequence
trip0,00:00:00,00:00:30,stop0,0
trip0,,,stop1,1
trip0,,,stop2,1
trip0,00:15:00,00:15:00,stop0,2
```

A completely unordered trip (i.e. a completely on-demand service using fixed stops as in the Dutch OVFlex, not really a single trip) would then have stop times like this:
```
trip_id,arrival_time,departure_time,stop_id,stop_sequence
trip0,,,stop0,0
trip0,,,stop1,0
trip0,,,stop2,0
trip1,,,stop3,0
```

Of course we might want some (technically redundant) flag at the trip or route level to confirm that this is not bad data, and that repeating sequence numbers are expected. A route flag indicating that a particular route is using the gtfs-flex extensions might be sufficient.

We could also attempt to limit the rejection of flex trips by legacy systems to a single route or trip, so the rest of the classic scheduled service in the feed would still be used. This could possibly be achieved by leaving the trip_ids for flex trips out of trips.txt. But this is assuming lots of things about how consumers validate and use data.

**Comment by barbeau** [comment]
I agree that we need to somehow flag flex data in existing tables so it's not consumed as "normal" service by legacy systems.

One down-side I see to repeating `stop_sequence` values is that `stop_sequence` is often used as a unique index to a stop in a trip (you can't use `stop_id` because you can have loop routes, etc. that visit a stop more than once).

A similar idea to flag stops but not use repeating `stop_sequence` values would be to use negative values for `stop_sequence`.

So this:

~~~
trip_id,arrival_time,departure_time,stop_id,stop_sequence
trip0,00:00:00,00:00:30,stop0,0
trip0,,,stop1,1
trip0,,,stop2,1
trip0,00:15:00,00:15:00,stop0,2
~~~

...would become:

~~~
trip_id,arrival_time,departure_time,stop_id,stop_sequence
trip0,00:00:00,00:00:30,stop0,0
trip0,,,stop1,-1
trip0,,,stop2,-2
trip0,00:15:00,00:15:00,stop0,3
~~~

**Comment by abyrd** [comment]
I don't think negative values can work, because then we lose the position of the unordered block within the overall ordered trip. 

The use of stop_sequence as a unique index (you could also say, use of (trip_id, stop_index) as a compound key) is an internal implementation detail specific to some systems and arguably shouldn't be a concern for a data exchange specification. Also, the fact that an existing system using such keys would break when consuming the new data is actually a desirable outcome from one point of view.

A system that is genuinely able to handle unordered trips will need to rethink its mechanisms for storing such trips anyway, grouping some of the stops together in mutually reachable sets that are themselves optionally situated in an ordered sequence. In some cases the routing will need to be completely different because there are not known travel times between these stops. For all these reasons I still tend to lean toward repeating sequence numbers for unordered blocks of stops.

**Comment by barbeau** [comment]
>I don't think negative values can work, because then we lose the position of the unordered block within the overall ordered trip.

In my example above, you could just take the absolute value of the stop_sequence values and that would allow you to retain order of the overall trip.  The negative value is just an indicator that those stops are unordered.

**Comment by thomastrillium** [comment]
Another solution we've considered is to make the unordered stops a multipoint geometry. Previously, I'd been concerned about how then to deal with unordered stop names, but @LeoFrachet has been thinking up some great solutions. 

Just so you're not surprised @abyrd I'll note that MobilityData has been engaging with me through conversation the last week and we're thinking up a few tweaks to the GTFS-flex. They'll be proposed on this repository and we can discuss.

Thanks so much for your engagement the last few weeks here. Your comments have been very insightful and driven home some of the core needs of the GTFS-flex project.

**Comment by t2gran** [comment]
I think the best option here is to repeat the stop_sequence as @abyrd has purposed.

An alternativ would be to reference a FlexibleArea in the `stop_id` field or better add a new column `flexibleArea_id`. Then each row must have a `stop_id` or `flexibleArea_id`, not both or none. This might be similar to "multipoint geometry", but I borrowed the terminology from the Transmodel, and by using `flexibleArea_id` we keep it open to what a flexible area is, group of unordered stops, deviation from a given path, any where inside a polygone...

The _flexible area_ should then be defined else where.

**Comment by t2gran** [comment]
By the way - here is an example of the NeTEx (Norwegian) profile:

https://rutebanken.atlassian.net/wiki/spaces/PUBLIC/pages/41811978/Bestillingstransport

I am sorry we don´t have a english translation, but I hope Google translate works well enough that you get the picture. Types are in english.

**Comment by thomastrillium** [comment]
> `flexibleArea_id`. Then each row must have a `stop_id` or `flexibleArea_id`, not both or none. This might be similar to "multipoint geometry", but I borrowed the terminology from the Transmodel, and by using `flexibleArea_id` we keep it open to what a flexible area is,

I think that's spot on and pretty similar to what we've come to in the proposed[ GTFS-flex v2](https://docs.google.com/document/d/1QVrijt2omNN_lvCkC0FmRhciVmWg-cJtNW_PqULc-Pw/edit#heading=h.84nzwlrotoj3)

In the draft, we've maintained everything in the stop_id column, but provided a flexible location location_type value.

**Comment by t2gran** [comment]
@thomastrillium thank you for the link to the v2, I was not aware of it. I will read trough it.

**Comment by thomastrillium** [comment]
sorry about that @t2gran ! we'll have the docs linked up better soon. :)
