### ISSUE TITLE
gtfs-flex-realtime

### ISSUE THREAD

**Issue by mpaine-act** [MobilityData/gtfs-flex#38]
Is there any plans for gtfs-flex-realtime?  I could see dynamic scheduling needing to modify the static data for on-demand transit solutions.

**Comment by thomastrillium** [comment]
great question @mpaine-act 

In the [GTFS-flex v2 draft](https://docs.google.com/document/d/1QVrijt2omNN_lvCkC0FmRhciVmWg-cJtNW_PqULc-Pw/edit#) which should supplant the current repo very soon, there is a GTFS-BookingTransactions spec extension that suggests the format of the real-time updates for on-demand services.

It is somewhat more "experimental" as there are more questions about the degree to which such APIs should be fully standardized, and whether they should fit into the framework of static flex fields like the BookingTransactions spec does. Your feedback would be appreciated.
