### ISSUE TITLE
Add semantic versioning to repository

### ISSUE THREAD

**Issue by scmcca** [MobilityData/gtfs-flex#45]
Add semantic versioning to [README.md](https://github.com/MobilityData/gtfs-flex/blob/master/README.md) to distinguish the implied versions of the spec and make it easier to navigate.

Suggested description:
> ### Versioning
> Semantic versions are established by a git tag in the form of `vX.Y` where `X.Y` is the version name. Multiple changes (commits) may be batched into a single new release.
> 
> A whole integer increase is used for breaking changes (MAJOR changes). A decimal increase is used for non-breaking changes (MINOR changes or patches).
> 
> Breaking changes include:
> - Removing or changing features.
> 
> Non-breaking changes include:
> - Adding features.

Tag commits with versions:
- e1832cf as v2.0
- 2dd3802 as v1.0

**Comment by scmcca** [comment]
@westontrillium I want to bring this back up for discussion. 

Is this something the Flex community would find useful to keep track of previous (and current) implementations? Especially as we are seeing more and more shifting changes to GTFS-Flex? 

If not I'll close the issues and PRs related to this (#44, #45, #57).

**Comment by westontrillium** [comment]
I do think this could be useful as a back-of-the-house indicator, especially when discussing changes between past versions. At the same time, however, it looks like Flex may be entering a phase wherein there are a lot of small changes being pushed to the master (unless we want to accumulate these small changes and then merge all at once eventually), so including semantic versioning could get cumbersome during this time.

At any rate, to avoid confusion, I think that the phrasing "GTFS-Flex" (sans version number) should always implicitly refer to whatever the most current version is in this repo, while version numbers should really only be referenced in the context of discussing versions in relation to one another (e.g. "the language added in v3.3 brings back the definition established in v2.0," etc.). I'd be interested to hear other's thoughts on this though!

**Comment by scmcca** [comment]
Sounds good to me. Especially:
>At any rate, to avoid confusion, I think that the phrasing "GTFS-Flex" (sans version number) should always implicitly refer to whatever the most current version is in this repo, while version numbers should really only be referenced in the context of discussing versions in relation to one another (e.g. "the language added in v3.3 brings back the definition established in v2.0," etc.). I'd be interested to hear other's thoughts on this though!

To review at a later point in time when we have something more stable.
