### ISSUE TITLE
Forbid arrival and departure times for on-demand point to point service

### ISSUE THREAD

**Issue by scmcca** [MobilityData/gtfs-flex#49]
Currently stop_times.arrival_time and .departure_time are forbidden if .stop_id refers to geojson areas. This is an ad-hoc way to say that arrival and departure times should not be defined for on-demand service, but does not capture point to point on demand service (i.e., point type polygons).

Therefore, a different approach should be considered for "hard coding" on-demand data in GTFS to avoid future conflicts.

**Comment by westontrillium** [comment]
I think the intention of locations.geojson was to only represent area-based polygons (whether that's a route deviation buffer zone, a contiguous demand-responsive service boundary, a single polygon with multiple isolated areas, etc.). From the spec: "Individual stops should be defined in `stops.txt`."

I've been assuming an on-demand point to point service (previously unordered stops in v1) would be represented by a location_group consisting of regular stops that has a single `start_pickup_drop_off_window`/`end_pickup_drop_off_window` with `pickup_type`/`drop_off_type≠0`. Could/should this kind of service be modeled a different way?

Representing an on-demand point to point service in this way would make arrival/departure times forbidden ("Forbidden when `stop_times.stop_id` references a `location_groups.locationg_group_id`"). Does that solve the issue?

**Comment by scmcca** [comment]
That makes sense! I hadn't thought through the data enough for the use case. Thanks!
