### ISSUE TITLE
backward compatibility w/stop_times.stop_id - polygons/areas in stop_times.txt

### ISSUE THREAD

**Issue by antrim** [MobilityData/gtfs-flex#6]
Referencing polygons in stop_times.txt poses an issue for backward compatibility because a stop_id needs to be referenced in each record. How about creating a stop_times_areas.txt or demand_response.txt that follows similar structure, including stop_sequences and references to trip_id?

**stop_times_areas.txt** file which contains the records with **start_service_area_id** and **end_service_area_id**. The schedule for a **trip_id** is expressed through the combination of these two files — **stop_sequence** numbers count up through both files. For an example, see the [gtfs-flexible sandbox](https://docs.google.com/spreadsheets/d/1GL2FBId1fIZltDa4k6SCWmJ8-D4jN3sfqdwFjKsErR4/edit#gid=95021656) example 5.A or “Green Mountain”.

**Comment by thomastrillium** [comment]
tagging @DerekEdwards on this issue.

This is the ambiguity I indicated in my notes to you, and a suggestion for clearing it up from @antrim

**Comment by antrim** [comment]
Tagging issue #9 - Open thread for discussion on backward compatibility.
