### ISSUE TITLE
Clarification: Pick up and drop off at the same flex location stop_time

### ISSUE THREAD

**Issue by leonardehrenfried** [MobilityData/gtfs-flex#65]
I'm currently fine-tuning the flex implementation in OTP2 and have been wondering about the following point:

If I have a service that has both fixed schedule and flex location stop_times in the following order:

1. Fixed schedule stop_time at stop A
2. Flex stop_time at flex zone B (pick up and drop off possible by calling ahead)
3. Fixed schedule stop_time at stop C

Currently the OTP code interprets this as follows: 

- you can get on the vehicle at zone B but since the stop_sequence needs to increase you cannot get off straight away inside zone B. 
- If you want to treat this trip as a taxi service that can pick up and drop off passengers anywhere in zone B before proceeding to stop C, you'd have to add a second, identical stop_time in zone B.

I cannot find anything in the spec that would clarify what the intention is. Should you be allowed to get on _and_ off at the same flex zone stop_time?

If so, how would you model a service that picks up or drops off passengers in the zone, but doesn't drive them from one point to another one inside the zone?

This actually also applies to trips that contain flex zones only: if you have a trip with two flex zones, can you get on _and_ off at the same stop_time?

One could argue that it doesn't make sense to get on and immediately off at the same "stop" but I recognise that this is a special case.

I'd love to hear your opinions!

cc @hannesj

**Comment by leonardehrenfried** [comment]
@hannesj, @westontrillium I wonder if the "Finnish use case" could be covered with the following stop_times:

1. Stop A: pickup and dropoff allowed
2. Zone B: dropoff allowed, pickup not allowed
3. Zone B: dropoff not allowed, pickup allowed
4. Stop C: pickup and dropoff allowed

Of course this requires strict ordering of the zone stop times. If you reverse them then you get the the intra-zone transport that is - according to the service rules - not allowed

Or am I missing something?

**Comment by hannesj** [comment]
Yes, that could be done 👍

**Comment by westontrillium** [comment]
@leonardehrenfried Aha, clever! I had not thought of doing that. Good thinking.

**Comment by leonardehrenfried** [comment]
Ok, seems like we have found a solution that everyone can live with.

I will update the OTP implementation to match the expectation.

Thanks everyone for the participation!

**Comment by gcamp** [comment]
Did a read this issue right : there was agreement on how data should be interpreted (👍 on that) but the spec was not clarified? Can we work on clarifying the spec?

**Comment by leonardehrenfried** [comment]
Yeah, sorry, I overeagerly closed the issue after everything was clear to myself. :/

I think a spec change would be very good.

I personally would be looking for a language like: "pick up and drop off inside the same location referenced by a single stop_time row are possible if no restrictions are applied".

However, I defer to @westontrillium on the precise phrasing as he's more knowledgeable about what terms are used in the rest of the spec.

At the end of the day I think it's hard to come up with sentence that is both clear and concise.

**Comment by leonardehrenfried** [comment]
Perhaps as requested in #54 an annotated example with for @hannesj would be a good idea but a link to this very issue might already be enough.

**Comment by westontrillium** [comment]
I've gone ahead and made a PR for the added language. Providing an annotated example could be taken care of under the umbrella of the MD effort to develop a tutorial document / Flex examples guideline.

**Comment by leonardehrenfried** [comment]
I've opened the first of a series of PRs that will bring OTP in line with the intention of the spec: https://github.com/opentripplanner/OpenTripPlanner/pull/3720

**Comment by westontrillium** [comment]
This issue can be closed. It has been resolved through conversation [here](https://github.com/google/transit/issues/337) and a subsequent commit by @omar-kabbani.

**Comment by tzujenchanmbd** [comment]
Closing this issue per the [comment](https://github.com/MobilityData/gtfs-flex/issues/65#issuecomment-1289464851) above. We can reopen [#337](https://github.com/google/transit/issues/337) if there is any concerns during adoption process later.
