### ISSUE TITLE
Clarification: Where exactly should the field zone_id in locations.geojson be added

### ISSUE THREAD

**Issue by leonardehrenfried** [MobilityData/gtfs-flex#68]
After reading the spec, I got a little confused about the precise nesting of the JSON properties in the `locations.json`. I'm pretty sure that it's just the indentation that is slightly off but I'd love some clarification.

Here is a screenshot how the table renders in my browser (Firefox on Linux):

![Screenshot from 2021-11-09 09-31-17](https://user-images.githubusercontent.com/151346/140890374-9607bb97-af56-4382-9f56-e0ecad5914cb.png)

Am I right in thinking that the fields `stop_name` and `stop_desc` are supposed to be indented the same way as `zone_id` and `stop_url`, namely that they are all fields of the the JSON object `properties`?

Secondly, the last bullet point just before the table says: "Every GeoJSON Feature must have a `properties` object, which may have the following keys:"

Then follow properties which should definitely _not_ be keys of the `properties` object. I think this sentence is left over from an earlier version of the spec where the structure of the table was different.

Am I seeing this correct?

**Comment by westontrillium** [comment]
@tsherlockcraig

**Comment by tsherlockcraig** [comment]
@leonardehrenfried your comments look right to me.

Proposed edit to the last bullet: "Every GeoJSON Feature should have objects and associated keys according to the table below:" or something like that?

@omar-kabbani could your team look at this?

**Comment by michellenguyenta** [comment]
@leonardehrenfried Good catch on that, on Mac OS Chrome the indentation appears to be correct. We are currently troubleshooting this problem with Firefox and depending on the result, we may reformat the indented lists of the markdown file. The indented lists are done using HTML which may be the source of the problem. 

@tsherlockcraig We've gone ahead and applied your proposed edit to the locations.geojson description.

**Comment by leonardehrenfried** [comment]
@michellenguyenta Thanks for pointing that out. I just checked and it indeed looks ok in Chrome and the source code of the markdown is identical for the rows. The problem is the `&emsp;` rather than `&nbsp;` because emsp allows line breaks, so the lines `stop_name` and `stop_desc` are broken into two.

**Comment by michellenguyenta** [comment]
@leonardehrenfried Thank you for the solution, we have made the changes to the table's indentation. You can see it properly rendered now on Firefox. Let us know if it works on your end too.

**Comment by leonardehrenfried** [comment]
Looks great. Thanks!
